/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rreader.gui;

/**
 *
 * @author leohonka
 */
public class ErrorDialog extends javax.swing.JDialog {
    public String error_text;
    /**
     * Creates new form ErrorDialog
     */
    public ErrorDialog(java.awt.Frame parent, boolean modal, String error_text) {
        super(parent, modal);
        initComponents();
        this.error_text = error_text;
        this.ErrorText.setText(error_text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorTitle = new javax.swing.JLabel();
        DismissButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ErrorText = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        ErrorTitle.setText("Error occurred");
        add(ErrorTitle, java.awt.BorderLayout.NORTH);

        DismissButton.setText("Dismiss");
        DismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DismissButtonActionPerformed(evt);
            }
        });
        add(DismissButton, java.awt.BorderLayout.SOUTH);

        ErrorText.setColumns(20);
        ErrorText.setRows(5);
        jScrollPane1.setViewportView(ErrorText);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void DismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DismissButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_DismissButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DismissButton;
    private javax.swing.JTextArea ErrorText;
    private javax.swing.JLabel ErrorTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
