/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rreader.gui;

/**
 *
 * @author leohonka
 */
public class RedditDialog extends javax.swing.JDialog {
    public AppWindow parent; 
    
    /**
     * Creates new form RedditDialog
     */
    public RedditDialog(AppWindow parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RedditTitle = new javax.swing.JLabel();
        RedditName = new javax.swing.JTextField();
        RedditButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        RedditTitle.setText("Select Reddit to read..");
        add(RedditTitle, java.awt.BorderLayout.NORTH);

        RedditName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedditNameActionPerformed(evt);
            }
        });
        add(RedditName, java.awt.BorderLayout.CENTER);

        RedditButton.setText("Start Reading");
        RedditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedditButtonActionPerformed(evt);
            }
        });
        add(RedditButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void RedditNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedditNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RedditNameActionPerformed

    private void RedditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedditButtonActionPerformed
        parent.setRedditName(RedditName.getText());
        setVisible(false);
        dispose();
    }//GEN-LAST:event_RedditButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RedditButton;
    private javax.swing.JTextField RedditName;
    private javax.swing.JLabel RedditTitle;
    // End of variables declaration//GEN-END:variables
}
